---
title: "Assignment 1"
author: "Jeremy Morris"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment Description
In this assignment, the student will

* find a data set they think is interesting
* create one or two visualizations using the tool of their choice
    * if desired, include a paragraph or two describing the context and conclusions drawn from the included visualizations
* upload the visualization to Canvas by the assigned due date

Groups have been defined in Canvas for assignment 1. The purpose of these groups is to discuss your visualizations and help students turn in an acceptable finished product. For assignment 1 there will be no grade for the group portion of this assignment.

# Supplemental Materials
By the time the assignment is due, we will have discussed the following information.

* Defining your audience
* Understanding what your audience needs to know
* Choosing the right chart type
* Details about various chart types
* Effective use of color in charts

Following is a list of websites that provide publicly available data.

* https://opendata.utah.gov/ 
* https://sqlbelle.com/2015/01/16/data-sets-for-bianalyticsvisualization-projects/
* https://www.reddit.com/r/datasets/ 

# Submission Criteria
Each student will turn in a PDF or HTML document in Canvas with the following information.

* Student Name
* Project Title
* Student's own data visualization
* (Optional) One or two paragraphs describing the context, meaning and interpretation of the included data visualization.

Points will be deducted if the following occur.

* More than one student turns in the same visualization.
* There are more than three visuals in the assignment.
* The written section is excessively long.
* The audience is poorly defined.
* The chart type does not aid in understanding the interpretation.
* Computations do not match their stated meaning.